=== openfabr/cdf/samples/packages/awscdk-typescript/src/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "NetworkSubnetDetail": {
            "properties": {
                "mask": {
                    "title": "mask",
                    "type": "number"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/NetworkSubnetType",
                    "title": "type"
                }
            },
            "title": "NetworkSubnetDetail",
            "type": "object"
        },
        "NetworkSubnetType": {
            "enum": [
                "isolated",
                "private",
                "public"
            ],
            "title": "NetworkSubnetType",
            "type": "string"
        },
        "PackageComponentConfigChoices": {
            "anyOf": [
                {
                    "$ref": "#/definitions/PackageComponentKeySoftwareConfig"
                },
                {
                    "$ref": "#/definitions/PackageComponentMessageQueueConfig"
                },
                {
                    "$ref": "#/definitions/PackageComponentMessageTopicConfig"
                },
                {
                    "$ref": "#/definitions/PackageComponentStorageBucketConfig"
                },
                {
                    "$ref": "#/definitions/PackageComponentStaticWebsiteHostingConfig"
                }
            ],
            "title": "PackageComponentConfigChoices"
        },
        "PackageComponentKeySoftwareConfig": {
            "properties": {
                "enabled": {
                    "title": "enabled",
                    "type": "boolean"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                },
                "rotation": {
                    "title": "rotation",
                    "type": "boolean"
                },
                "spec": {
                    "enum": [
                        "ECC_NIST_P521",
                        "ECC_SECG_P256K1",
                        "RSA_4096",
                        "SYMMETRIC_DEFAULT"
                    ],
                    "title": "spec",
                    "type": "string"
                },
                "usage": {
                    "enum": [
                        "ENCRYPT_DECRYPT",
                        "SIGN_VERIFY"
                    ],
                    "title": "usage",
                    "type": "string"
                }
            },
            "title": "PackageComponentKeySoftwareConfig",
            "type": "object"
        },
        "PackageComponentMessageQueueConfig": {
            "properties": {
                "dlq": {
                    "title": "dlq",
                    "type": "number"
                },
                "fifo": {
                    "title": "fifo",
                    "type": "boolean"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                }
            },
            "title": "PackageComponentMessageQueueConfig",
            "type": "object"
        },
        "PackageComponentMessageTopicConfig": {
            "properties": {
                "fifo": {
                    "title": "fifo",
                    "type": "boolean"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                }
            },
            "title": "PackageComponentMessageTopicConfig",
            "type": "object"
        },
        "PackageComponentStaticWebsiteHostingConfig": {
            "properties": {
                "domain": {
                    "title": "domain",
                    "type": "string"
                },
                "hostName": {
                    "title": "hostName",
                    "type": "string"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                }
            },
            "title": "PackageComponentStaticWebsiteHostingConfig",
            "type": "object"
        },
        "PackageComponentStorageBucketConfig": {
            "properties": {
                "blockPublicAccess": {
                    "enum": [
                        "BLOCK_ACLS",
                        "BLOCK_ALL"
                    ],
                    "title": "blockPublicAccess",
                    "type": "string"
                },
                "bucketName": {
                    "title": "bucketName",
                    "type": "string"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                }
            },
            "title": "PackageComponentStorageBucketConfig",
            "type": "object"
        },
        "PackageGeneralConfig": {
            "properties": {
                "name": {
                    "title": "name",
                    "type": "string"
                }
            },
            "title": "PackageGeneralConfig",
            "type": "object"
        },
        "PackageNetworkConfig": {
            "properties": {
                "cidr": {
                    "description": "CIDR notation, either IPv4 or IPv6.",
                    "title": "cidr",
                    "type": "string"
                },
                "domain": {
                    "title": "domain",
                    "type": "string"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                },
                "subnets": {
                    "items": {
                        "$ref": "#/definitions/NetworkSubnetDetail"
                    },
                    "title": "subnets",
                    "type": "array"
                },
                "zones": {
                    "description": "Number of availability zones.",
                    "title": "zones",
                    "type": "number"
                }
            },
            "title": "PackageNetworkConfig",
            "type": "object"
        },
        "PackageRelationConfig": {
            "properties": {
                "bidi": {
                    "title": "bidi",
                    "type": "boolean"
                },
                "finish": {
                    "title": "finish",
                    "type": "string"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                },
                "start": {
                    "title": "start",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/RelationTyping",
                    "title": "type"
                }
            },
            "title": "PackageRelationConfig",
            "type": "object"
        },
        "PackageServiceContainerEcsConfig": {
            "properties": {
                "application": {
                    "$ref": "#/definitions/ServiceApplicationType",
                    "title": "application"
                },
                "containerImageName": {
                    "title": "containerImageName",
                    "type": "string"
                },
                "containerRegistry": {
                    "title": "containerRegistry",
                    "type": "string"
                },
                "cpu": {
                    "title": "cpu",
                    "type": "number"
                },
                "mem": {
                    "title": "mem",
                    "type": "number"
                },
                "name": {
                    "title": "name",
                    "type": "string"
                },
                "replicas": {
                    "title": "replicas",
                    "type": "number"
                }
            },
            "title": "PackageServiceContainerEcsConfig",
            "type": "object"
        },
        "RelationTyping": {
            "enum": [
                "ADMIN_KEY",
                "DECRYPT_KEY",
                "ENCRYPT_KEY",
                "PUBLISH_TOPIC",
                "READ_OBJECT",
                "RECEIVE_QUEUE",
                "SEND_QUEUE",
                "SUBSCRIBE_TOPIC",
                "WRITE_OBJECT"
            ],
            "title": "RelationTyping",
            "type": "string"
        },
        "RuntimeConfig<PackageServiceContainerEcsConfig>": {
            "description": "Concrete class for a group of services sharing the same *runtime*.",
            "properties": {
                "config": {
                    "$ref": "#/definitions/PackageServiceContainerEcsConfig",
                    "description": "The fallback config that applies to all services defined for the runtime.",
                    "title": "config"
                },
                "details": {
                    "description": "A list of services sharing the same runtime.",
                    "items": {
                        "$ref": "#/definitions/PackageServiceContainerEcsConfig"
                    },
                    "title": "details",
                    "type": "array"
                },
                "name": {
                    "description": "Name of the runtime.",
                    "title": "name",
                    "type": "string"
                },
                "subtype": {
                    "description": "Subtype of the runtime.",
                    "title": "subtype",
                    "type": "string"
                },
                "type": {
                    "description": "Type of the runtime.",
                    "title": "type",
                    "type": "string"
                }
            },
            "title": "RuntimeConfig<PackageServiceContainerEcsConfig>",
            "type": "object"
        },
        "ServiceApplicationType": {
            "enum": [
                "PUBLIC",
                "TASK"
            ],
            "title": "ServiceApplicationType",
            "type": "string"
        },
        "TraitConfig<PackageComponentConfigChoices>": {
            "description": "Concrete class for a group of components sharing the same *trait*.",
            "properties": {
                "config": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/PackageComponentKeySoftwareConfig"
                        },
                        {
                            "$ref": "#/definitions/PackageComponentMessageQueueConfig"
                        },
                        {
                            "$ref": "#/definitions/PackageComponentMessageTopicConfig"
                        },
                        {
                            "$ref": "#/definitions/PackageComponentStorageBucketConfig"
                        },
                        {
                            "$ref": "#/definitions/PackageComponentStaticWebsiteHostingConfig"
                        }
                    ],
                    "description": "The fallback config that applies to all components defined for the trait.",
                    "title": "config"
                },
                "details": {
                    "description": "A list of components sharing the same trait.",
                    "items": {
                        "$ref": "#/definitions/PackageComponentConfigChoices"
                    },
                    "title": "details",
                    "type": "array"
                },
                "name": {
                    "description": "Name of the trait.",
                    "title": "name",
                    "type": "string"
                },
                "subtype": {
                    "description": "Subtype of the trait.",
                    "title": "subtype",
                    "type": "string"
                },
                "type": {
                    "description": "Type of the trait.",
                    "title": "type",
                    "type": "string"
                }
            },
            "title": "TraitConfig<PackageComponentConfigChoices>",
            "type": "object"
        }
    },
    "description": "Concrete class that models the configuration for an infra project when using a package.\nIt has 5 top-level sections (general, network, components, services and relations), each of which is expected to extended by packages for their own needs.",
    "properties": {
        "components": {
            "description": "Top-level **components** section which carries a list of *trait* sub-sections.",
            "items": {
                "$ref": "#/definitions/TraitConfig<PackageComponentConfigChoices>"
            },
            "title": "components",
            "type": "array"
        },
        "general": {
            "$ref": "#/definitions/PackageGeneralConfig",
            "description": "Top-level **general** section.",
            "title": "general"
        },
        "network": {
            "$ref": "#/definitions/PackageNetworkConfig",
            "description": "Top-level **network** section.",
            "title": "network"
        },
        "relations": {
            "description": "Top-level **relations** section which carries a list of *relation* sub-section.",
            "items": {
                "$ref": "#/definitions/PackageRelationConfig"
            },
            "title": "relations",
            "type": "array"
        },
        "services": {
            "description": "Top-level **services** section which carries a list of *runtime* sub-sections.",
            "items": {
                "$ref": "#/definitions/RuntimeConfig<PackageServiceContainerEcsConfig>"
            },
            "title": "services",
            "type": "array"
        }
    },
    "type": "object"
}

=== openfabr/cdf/samples/packages/pulumi-typescript/tests/short-config.json
{
  "general": {
    "name": "fabr-sample"
  },
  "network": {
    "name": "default-vpc",
    "vpc": {
      "name": "default-vpc"
    },
    "domain": "acme.com"
  },
  "components": [
    {
      "name": "static-website-hosting",
      "type": "distribution",
      "subtype": "website",
      "details": [
        {
          "name": "test-static-website",
          "hostName": "staticsite",
          "domain": "test.fabrhq.dev"
        }
      ]
    }
  ],
  "services": [
    {
      "name": "ecs-farget",
      "type": "container",
      "subtype": "ecs",
      "details": [
        {
          "name": "web-service",
          "application": "PUBLIC",
          "dockerfilePath": "/test-apps/api",
          "cpu": 512,
          "mem": 2048,
          "replicas": 2
        }
      ]
    }
  ],
  "relations": [
  ]
}

=== openfabr/cdf/samples/projects/awscdk-typescript/lib/privates3.config.json
{
  "general": {
    "name": "sample"
  },
  "network": {
    "name": "main-vpc",
    "domain": "acme.com",
    "cidr": "192.168.0.0/16",
    "zones": 2,
    "subnets": [
      {
        "name": "private-subnet",
        "type": "private",
        "mask": 24
      },
      {
        "name": "public-subnet",
        "type": "public",
        "mask": 24
      }
    ]
  },
  "components": [
    {
      "name": "s3-bucket-private",
      "type": "storage",
      "subtype": "bucket",
      "details": [
        {
          "name": "fabr-bucket-1",
          "blockPublicAccess": "BlockPublicAccess.BLOCK_ALL"
        }
      ]
    }
  ],
  "services": [
  ],
  "relations": [
  ]
}

=== openfabr/cdf/samples/projects/cdktf-typescript/lib/config.json
{
  "general": {
    "name": "cdktf-sample",
    "defaultRegion": "lon",
    "defaultRegionDatacenter": "lon1"
  },
  "network": {
    "name": "unsupported"
  },
  "components": [

  ],
  "services": [
    {
      "name": "do-app",
      "type": "app",
      "subtype": "service",
      "details": [
        {
          "name": "testapi",
          "dockerfilePath": "Dockerfile",
          "dockerhubRegistryName": "janaka",
          "containerRegistryRepoName": "test-api",
          "replicas": 1
        }
      ]
    }
  ],
  "relations": []
}

=== openfabr/cdf/samples/packages/awscdk-typescript/test/component-distribution-staticwebsite.config.json
{
  "general": {
    "name": "sample"
  },
  "network": {
    "name": "main-vpc",
    "domain": "acme.com",
    "cidr": "192.168.0.0/16",
    "zones": 2,
    "subnets": [
      {
        "name": "private-subnet",
        "type": "private",
        "mask": 24
      },
      {
        "name": "public-subnet",
        "type": "public",
        "mask": 24
      }
    ]
  },
  "components": [
    {
      "name": "static-website-hosting",
      "type": "distribution",
      "subtype": "staticWebsite",
      "details": [
        {
          "name": "test-static-website",
          "hostName": "staticsite",
          "domain": "test.fabrhq.dev"
        }
      ]
    }
  ],
  "services": [
   
  ],
  "relations": [
  ]
}

=== openfabr/cdf/samples/packages/awscdk-typescript/test/container-ecs.config.json
{
  "general": {
    "name": "sample"
  },
  "network": {
    "name": "main-vpc",
    "domain": "acme.com",
    "cidr": "192.168.0.0/16",
    "zones": 2,
    "subnets": [
      {
        "name": "private-subnet",
        "type": "private",
        "mask": 24
      },
      {
        "name": "public-subnet",
        "type": "public",
        "mask": 24
      }
    ]
  },
  "components": [
  ],
  "services": [
    {
      "name": "ecs-fargate",
      "type": "container",
      "subtype": "ecs",
      "details": [
        {
          "name": "web-service",
          "application": "PUBLIC",
          "contianerRrgistry": "",
          "containerImageName": "",
          "cpu": 512,
          "mem": 2048,
          "replicas": 2
        }
      ]
    }
  ],
  "relations": [
  ]
}

=== openfabr/cdf/samples/projects/awscdk-typescript/lib/private-s3.config.json
{
  "general": {
    "name": "sample"
  },
  "network": {
    "name": "nothing"
  },
  "components": [
    {
      "name": "s3-bucket-private",
      "type": "store",
      "subtype": "object",
      "details": [
        {
          "name": "fabr-bucket-1",
          "blockPublicAccess": "BlockPublicAccess.BLOCK_ALL"
        }
      ]
    }
  ],
  "services": [
  ],
  "relations": [
  ]
}

=== openfabr/cdf/samples/packages/awscdk-typescript/test/configB.json
{
  "general": {
    "name": "sample"
  },
  "network": {
    "name": "main-vpc",
    "domain": "acme.com",
    "cidr": "192.168.0.0/16",
    "zones": 2,
    "subnets": [
      {
        "name": "private-subnet",
        "type": "private",
        "mask": 24
      },
      {
        "name": "public-subnet",
        "type": "public",
        "mask": 24
      }
    ]
  },
  "components": [
    {
      "name": "static-website-hosting",
      "type": "distribution",
      "subtype": "website",
      "details": [
        {
          "name": "test-static-website",
          "hostName": "staticsite",
          "domain": "test.fabrhq.dev"
        }
      ]
    }
  ],
  "services": [
    {
      "name": "ecs-farget",
      "type": "container",
      "subtype": "ecs",
      "details": [
        {
          "name": "web-service",
          "application": "PUBLIC",
          "dockerfilePath": "/test-apps/api",
          "cpu": 512,
          "mem": 2048,
          "replicas": 2
        }
      ]
    }
  ],
  "relations": [
  ]
}

=== openfabr/cdf/samples/packages/awscdk-typescript/test/long-config.json
{
  "general": {
    "name": "sample"
  },
  "network": {
    "name": "main-vpc",
    "domain": "acme.com",
    "cidr": "192.168.0.0/16",
    "zones": 2,
    "subnets": [
      {
        "name": "private-subnet",
        "type": "private",
        "mask": 24
      },
      {
        "name": "public-subnet",
        "type": "public",
        "mask": 24
      }
    ]
  },
  "components": [
    {
      "name": "s3",
      "type": "store",
      "subtype": "object",
      "details": [
        {
          "name": "work-bucket",
          "blockPublicAccess": "BlockPublicAccess.BLOCK_ALL"
        }
      ]
    },
    {
      "name": "sqs",
      "type": "message",
      "subtype": "queue",
      "details": [
        {
          "name": "work-queue",
          "fifo": true,
          "dlq": 1000
        }
      ]
    },
    {
      "name": "sns",
      "type": "message",
      "subtype": "topic",
      "details": [
        {
          "name": "work-topic",
          "fifo": false
        }
      ]
    },
    {
      "name": "kms",
      "type": "key",
      "subtype": "software",
      "details": [
        {
          "name": "work-key",
          "spec": "RSA_4096",
          "usage": "ENCRYPT_DECRYPT",
          "enabled": true,
          "rotation": false
        }
      ]
    }
  ],
  "services": [
    {
      "name": "ecs-farget",
      "type": "container",
      "subtype": "ecs",
      "details": [
        {
          "name": "web-service",
          "application": "PUBLIC",
          "cpu": 512,
          "mem": 2048,
          "replicas": 2
        },
        {
          "name": "task-service",
          "application": "TASK",
          "cpu": 512,
          "mem": 1024,
          "replicas": 1
        }
      ]
    }
  ],
  "relations": [
    {
      "type": "PUBLISH_TOPIC",
      "name": "web-service-publishing-topic",
      "start": "web-service",
      "finish": "work-topic",
      "bidi": false
    }, 
    {
      "type": "SUBSCRIBE_TOPIC",
      "name": "task-queue-subscribe-topic",
      "start": "work-queue",
      "finish": "work-topic",
      "bidi": false
    }, 
    {
      "type": "RECEIVE_QUEUE",
      "name": "task-service-receive-queue",
      "start": "task-service",
      "finish": "work-queue",
      "bidi": false
    }, 
    {
      "type": "ENCRYPT_KEY",
      "name": "task-service-encrypt-key",
      "start": "task-service",
      "finish": "work-key",
      "bidi": false
    }, 
    {
      "type": "DECRYPT_KEY",
      "name": "task-service-decrypt-key",
      "start": "task-service",
      "finish": "work-key",
      "bidi": false
    }, 
    {
      "type": "READ_OBJECT",
      "name": "task-service-read-object",
      "start": "task-service",
      "finish": "work-bucket",
      "bidi": false
    }, 
    {
      "type": "WRITE_OBJECT",
      "name": "task-service-write-object",
      "start": "web-service",
      "finish": "work-bucket",
      "bidi": false
    }, 
    {
      "type": "ADMIN_KEY",
      "name": "web-service-admin-key",
      "start": "web-service",
      "finish": "work-key",
      "bidi": false
    }
  ]
}
