=== openfabr/cdf/docs/references/typescript/2.0.0/manifest.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "CloudVendor": {
            "description": "A list of cloud vendors.\nThe purpose of defining them is to regulate their names throughout the framework and all packages.",
            "enum": [
                "ALI",
                "AWS",
                "AZR",
                "CF",
                "DO",
                "GCP"
            ],
            "title": "CloudVendor",
            "type": "string"
        },
        "ComponentType": {
            "description": "Interface that represents a typing classification for components.",
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "subtype": {
                    "title": "subtype",
                    "type": "string"
                },
                "type": {
                    "title": "type",
                    "type": "string"
                }
            },
            "title": "ComponentType",
            "type": "object"
        },
        "ComponentsInfo": {
            "description": "Interface that represents information about available component constructs.",
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "types": {
                    "additionalProperties": {
                        "$ref": "#/definitions/ComponentType"
                    },
                    "description": "Available types and subtypes for components, keyed by a unique identifier among all components/services/relations.",
                    "title": "types",
                    "type": "object"
                }
            },
            "title": "ComponentsInfo",
            "type": "object"
        },
        "ConstructsInfo": {
            "description": "Interface that represents information about custom (code blocks) construct.\nMost notably it includes a reference to the code template.",
            "properties": {
                "components": {
                    "$ref": "#/definitions/ComponentsInfo",
                    "description": "Information about components.",
                    "title": "components"
                },
                "custom": {
                    "$ref": "#/definitions/CustomInfo",
                    "description": "Information about optional custom (code blocks).\nMissing this field implies that the package does NOT support custom code blocks.",
                    "title": "custom"
                },
                "network": {
                    "$ref": "#/definitions/NetworkInfo",
                    "description": "Information about optional network.\nMissing this field implies that the package does NOT support customisable virtual network.",
                    "title": "network"
                },
                "relations": {
                    "$ref": "#/definitions/RelationsInfo",
                    "description": "Information about relations.",
                    "title": "relations"
                },
                "schema": {
                    "description": "The reference to the json schema file for creating a valid json config when using the package.",
                    "title": "schema",
                    "type": "string"
                },
                "services": {
                    "$ref": "#/definitions/ServicesInfo",
                    "description": "Information about services.",
                    "title": "services"
                }
            },
            "title": "ConstructsInfo",
            "type": "object"
        },
        "CustomInfo": {
            "description": "Interface that represents information about custom (code blocks) construct.\nMost notably it includes a reference to the code template.",
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "template": {
                    "description": "The reference to the code template file for creating a valid custom code block when using the package.",
                    "title": "template",
                    "type": "string"
                }
            },
            "title": "CustomInfo",
            "type": "object"
        },
        "NetworkInfo": {
            "description": "Interface that represents information about network construct.",
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                }
            },
            "title": "NetworkInfo",
            "type": "object"
        },
        "RelationType": {
            "description": "Interface that represents a typing classification for relations.",
            "properties": {
                "bidi": {
                    "title": "bidi",
                    "type": "boolean"
                },
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "finish": {
                    "title": "finish",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "label": {
                    "title": "label",
                    "type": "string"
                },
                "start": {
                    "title": "start",
                    "type": "string"
                }
            },
            "title": "RelationType",
            "type": "object"
        },
        "RelationsInfo": {
            "description": "Interface that represents information about available relation constructs, keyed by a unique identifier among all components/services/relations.\nIt relies on the typing definitions in both {@link ComponentInfo} and {@link ServicesInfo}.",
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "types": {
                    "additionalProperties": {
                        "$ref": "#/definitions/RelationType"
                    },
                    "description": "Available relations between a specific component/service and another component/service.\nBoth the `start` and `finish` points here refer to the keys defined in `components` and `services` fields.",
                    "title": "types",
                    "type": "object"
                }
            },
            "title": "RelationsInfo",
            "type": "object"
        },
        "ServiceType": {
            "description": "Interface that represents a typing classification for services.\nIn particular, it contains a field for deployment instructions for the type of services defined.",
            "properties": {
                "deployment": {
                    "description": "The deployment instructions.\nThis is normally in plain text; markdown can be used too.",
                    "title": "deployment",
                    "type": "string"
                },
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "label": {
                    "title": "label",
                    "type": "string"
                },
                "subtype": {
                    "title": "subtype",
                    "type": "string"
                },
                "type": {
                    "title": "type",
                    "type": "string"
                }
            },
            "title": "ServiceType",
            "type": "object"
        },
        "ServicesInfo": {
            "description": "Interface that represents information about available service constructs.",
            "properties": {
                "description": {
                    "title": "description",
                    "type": "string"
                },
                "icon": {
                    "title": "icon",
                    "type": "string"
                },
                "types": {
                    "additionalProperties": {
                        "$ref": "#/definitions/ServiceType"
                    },
                    "description": "Available types and subtypes for services, keyed by a unique identifier among all components/services/relations.",
                    "title": "types",
                    "type": "object"
                }
            },
            "title": "ServicesInfo",
            "type": "object"
        },
        "SupportInfo": {
            "description": "Interface that offers support information about the package.",
            "properties": {
                "email": {
                    "description": "The support email address of the package.",
                    "title": "email",
                    "type": "string"
                },
                "phone": {
                    "description": "The support phone number of the package.",
                    "title": "phone",
                    "type": "string"
                },
                "url": {
                    "description": "The URL to the support site of the package.",
                    "title": "url",
                    "type": "string"
                }
            },
            "title": "SupportInfo",
            "type": "object"
        },
        "ToolingInfo": {
            "description": "Interface that offers information about IaC tooling.",
            "properties": {
                "command": {
                    "description": "The shell command to run deployment with the package.",
                    "title": "command",
                    "type": "string"
                },
                "language": {
                    "$ref": "#/definitions/ToolingLanguage",
                    "description": "The supported IaC language.",
                    "title": "language"
                },
                "runtime": {
                    "$ref": "#/definitions/ToolingRuntime",
                    "description": "The supported IaC runtime.",
                    "title": "runtime"
                },
                "vendors": {
                    "description": "The supported cloud vendors.\nUsually a package chooses support one vendor but some choose to have multiple-vendor support.",
                    "items": {
                        "$ref": "#/definitions/CloudVendor"
                    },
                    "title": "vendors",
                    "type": "array"
                }
            },
            "title": "ToolingInfo",
            "type": "object"
        },
        "ToolingLanguage": {
            "description": "A list of IaC languages.\nThe purpose of defining them is to regulate their names throughout the framework and all packages.",
            "enum": [
                "csharp",
                "custom",
                "go",
                "java",
                "python",
                "typescript"
            ],
            "title": "ToolingLanguage",
            "type": "string"
        },
        "ToolingRuntime": {
            "description": "A list of IaC runtime.\nThe purpose of defining them is to regulate their names throughout the framework and all packages.",
            "enum": [
                "awscdk",
                "cdktf",
                "custom",
                "pulumi"
            ],
            "title": "ToolingRuntime",
            "type": "string"
        }
    },
    "description": "Interface for modelling a package manifest json file that provides informations about the package.\nCrucially it also carries two references respectively to a) a json schema file for validating json config files and b) a template file for custom code blocks.",
    "properties": {
        "cdf": {
            "description": "The version of OpenFABR CDF that this package is compatible with, following semantic versioning.",
            "title": "cdf",
            "type": "string"
        },
        "constructs": {
            "$ref": "#/definitions/ConstructsInfo",
            "description": "Information about constructs defined in the package.",
            "title": "constructs"
        },
        "description": {
            "description": "The description of the package.",
            "title": "description",
            "type": "string"
        },
        "icon": {
            "title": "icon",
            "type": "string"
        },
        "identifier": {
            "description": "The unique identifier of the package.",
            "title": "identifier",
            "type": "string"
        },
        "license": {
            "description": "The SPDX license identifier for the license that the package is released under.",
            "title": "license",
            "type": "string"
        },
        "name": {
            "description": "The descriptive name of the package.",
            "title": "name",
            "type": "string"
        },
        "support": {
            "$ref": "#/definitions/SupportInfo",
            "description": "Information about the support provided for the package.",
            "title": "support"
        },
        "tooling": {
            "$ref": "#/definitions/ToolingInfo",
            "description": "Information about tooling the package relies on.",
            "title": "tooling"
        },
        "vendor": {
            "description": "The author of the package.",
            "title": "vendor",
            "type": "string"
        }
    },
    "type": "object"
}

=== openfabr/cdf/samples/packages/cdktf-typescript/src/cdf.manifest.json
{
  "$schema": "https://openfabr.github.io/cdf/references/typescript/2.0.0/manifest.schema.json",
  "identifier": "cdktf-typescript",
  "vendor": "OpenFABR",
  "license": "AGPL-3.0-only",
  "cdf": "^2.0.0",
  "name": "cdktf-typescript",
  "description": "A sample package using cdktf with TypeScript",
  "support": {
    "email": "open@fabr.ltd",
    "url": "https://open.fabrhq.com"
  },
  "tooling": {
    "command": "cdktf deploy",
    "runtime": "cdktf",
    "language": "typescript",
    "vendors": [
      "DO"    
    ]
  },
  "constructs": {
    "schema": "schema.json",
    "network": {
      "icon": "fas:network-wired"
    },
    "components": {
      "types": {
      }
    },
    "services": {
      "types": {
        "APP_SERVICE": { "type": "app", "subtype": "service", "deployment": "Use a container registry per service to trigger deployment", "icon": "fas:cube", "description": "Container service deployment via DO App Service"}
      }
    },
    "relations": {
      "types": {
      }
    },
    "custom": {
      "icon": "fas:code",
      "template": "template.ts"
    }
  }
}

=== openfabr/cdf/core/typescript/src/lib/metadata-normal.spec.json
{
  "identifier": "fabr-cdktf-gcp",
  "vendor": "FABR",
  "license": "UNLICENSED",
  "cdf": "1.x",
  "name": "A test package built by CDKTF for AWS",
  "description": "This package is for testing only",
  "support": {
    "email": "hello@abc.com",
    "phone": "0800123456789"
  },
  "tooling": {
    "command": "cdktf deploy",
    "runtime": "cdktf",
    "language": "typescript"
  },
  "constructs": {
    "schema": "schema.json",
    "network": {
      "icon": "https://abc.com/network.png"
    },
    "components": {
      "hello": { "type": "chinese", "subtype": "mandarin" },
      "fizz": { "type": "city", "subtype": "hong-kong" }
    },
    "services": {
      "world": { "type": "solar-system", "subtype": "earth" },
      "buzz": { "type": "country", "subtype": "morocco" }

    },
    "relations": {
      "hello": "world",
      "fizz": "buzz"
    },
    "custom": {
      "icon": "https://abc.com/code.png",
      "template": "template.ts"
    }
  }
}

=== openfabr/cdf/core/typescript/src/lib/metadata-minimal.spec.json
{
  "identifier": "fabr-cdktf-gcp",
  "vendor": "FABR",
  "license": "UNLICENSED",
  "cdf": "1.x",
  "tooling": {
    "command": "cdktf deploy",
    "runtime": "cdktf",
    "language": "typescript"
  },
  "constructs": {
    "schema": "schema.json",
    "network": {},
    "components": {
      "hello": { "type": "chinese", "subtype": "mandarin" },
      "fizz": { "type": "city", "subtype": "hong-kong" }
    },
    "services": {
      "world": { "type": "solar-system", "subtype": "earth" },
      "buzz": { "type": "country", "subtype": "morocco" }

    },
    "relations": {
      "hello": "world",
      "fizz": "buzz"
    },
    "custom": {
      "template": "template.ts"
    }
  }
}

=== openfabr/cdf/samples/packages/awscdk-typescript/src/cdf.manifest.json
{
  "$schema": "https://openfabr.github.io/cdf/references/typescript/1.3.0/manifest.schema.json",
  "identifier": "awscdk-typescript",
  "vendor": "OpenFABR",
  "license": "AGPL-3.0-only",
  "cdf": "^1.2.0",
  "name": "awscdk-typescript",
  "description": "A sample package using AWS CDK with TypeScript",
  "support": {
    "email": "open@fabr.ltd",
    "url": "https://open.fabrhq.com"
  },
  "tooling": {
    "command": "cdk deploy",
    "runtime": "awscdk",
    "language": "typescript",
    "vendors": [
      "AWS"
    ]
  },
  "constructs": {
    "schema": "schema.json",
    "network": {
      "icon": "fas:network-wired"
    },
    "components": {
      "types": {
        "KEY_SOFTWARE": { "type": "key", "subtype": "software", "icon": "fas:key", "description": "A software-based key in key management components" },
        "MESSAGE_TOPIC": { "type": "message", "subtype": "topic", "icon": "fas:comment-dots", "description": "A topic in messaging components" },
        "MESSAGE_QUEUE": { "type": "message", "subtype": "queue", "icon": "fas:grip-lines", "description": "A queue in messaging components" },
        "STORE_OBJECT": { "type": "store", "subtype": "object", "icon": "fas:book", "description": "An object store in storage components" },
        "DISTRIBUTION_WEBSITE": { "type": "distribution", "subtype": "website", "icon": "fas:share-alt", "description": "A static website in distribution components" }
      }
    },
    "services": {
      "types": {
        "CONTAINER_ECS": { "type": "container", "subtype": "ecs", "deployment": "Use AWS ECR per service to trigger deployment", "icon": "fas:cube", "description": "Container runtime via AWS ECS" }
      }
    },
    "relations": {
      "types": {
        "ENCRYPT_KEY": { "start": "CONTAINER_ECS", "finish": "KEY_SOFTWARE", "bidi": false },
        "DECRYPT_KEY": { "start": "CONTAINER_ECS", "finish": "KEY_SOFTWARE", "bidi": false },
        "ADMIN_KEY": { "start": "CONTAINER_ECS", "finish": "KEY_SOFTWARE", "bidi": false },
        "PUBLISH_TOPIC": { "start": "CONTAINER_ECS", "finish": "MESSAGE_TOPIC", "bidi": false },
        "SUBSCRIBE_TOPIC": { "start": "MESSAGE_QUEUE", "finish": "MESSAGE_TOPIC", "bidi": false },
        "SEND_QUEUE": { "start": "CONTAINER_ECS", "finish": "MESSAGE_QUEUE", "bidi": false },
        "RECEIVE_QUEUE": { "start": "CONTAINER_ECS", "finish": "MESSAGE_QUEUE", "bidi": false },
        "READ_OBJECT": { "start": "CONTAINER_ECS", "finish": "STORE_OBJECT", "bidi": false },
        "WRITE_OBJECT": { "start": "CONTAINER_ECS", "finish": "STORE_OBJECT", "bidi": false }
      }
    },
    "custom": {
      "icon": "fas:code",
      "template": "template.ts"
    }
  }
}

=== openfabr/cdf/samples/packages/pulumi-typescript/src/cdf.manifest.json
{
  "$schema": "https://openfabr.github.io/cdf/references/typescript/2.0.0/manifest.schema.json",
  "identifier": "pulumi-typescript",
  "vendor": "OpenFABR",
  "license": "AGPL-3.0-only",
  "cdf": "^2.0.0",
  "name": "pulumi-typescript",
  "description": "A sample package using Pulumi with TypeScript",
  "support": {
    "email": "open@fabr.ltd",
    "url": "https://open.fabrhq.com"
  },
  "tooling": {
    "command": "pulumi up",
    "runtime": "pulumi",
    "language": "typescript",
    "vendors": [
      "AWS"
    ]
  },
  "constructs": {
    "schema": "schema.json",
    "network": {
      "icon": "fas:network-wired"
    },
    "components": {
      "types": {
        "KEY_SOFTWARE": { "type": "key", "subtype": "software", "icon": "fas:key", "description": "A software-based key in key management components" },
        "MESSAGE_TOPIC": { "type": "message", "subtype": "topic", "icon": "fas:comment-dots", "description": "A topic in messaging components" },
        "MESSAGE_QUEUE": { "type": "message", "subtype": "queue", "icon": "fas:grip-lines", "description": "A queue in messaging components" },
        "STORE_OBJECT": { "type": "store", "subtype": "object", "icon": "fas:book", "description": "An object store in storage components" }
      }
    },
    "services": {
      "types": {
        "CONTAINER_ECS": { "type": "container", "subtype": "ecs", "deployment": "Use AWS ECR per service to trigger deployment", "icon": "fas:cube", "description": "Container runtime via AWS ECS" },
        "DISTRIBUTION_WEBSITE": { "type": "distribution", "subtype": "website", "deployment": "Upload build static website files to the S3 bucket. Using the AWS CLI is one recommended appproach `aws s3 sync <source_folder> s3://<bucket_name> --delete --acl public-read`", "icon": "fas:share-alt", "description": "A static website in a distribution service" }
      }
    },
    "relations": {
      "types": {
        "ENCRYPT_KEY": { "start": "CONTAINER_ECS", "finish": "KEY_SOFTWARE", "bidi": false },
        "DECRYPT_KEY": { "start": "CONTAINER_ECS", "finish": "KEY_SOFTWARE", "bidi": false },
        "ADMIN_KEY": { "start": "CONTAINER_ECS", "finish": "KEY_SOFTWARE", "bidi": false },
        "PUBLISH_TOPIC": { "start": "CONTAINER_ECS", "finish": "MESSAGE_TOPIC", "bidi": false },
        "SUBSCRIBE_TOPIC": { "start": "MESSAGE_QUEUE", "finish": "MESSAGE_TOPIC", "bidi": false },
        "SEND_QUEUE": { "start": "CONTAINER_ECS", "finish": "MESSAGE_QUEUE", "bidi": false },
        "RECEIVE_QUEUE": { "start": "CONTAINER_ECS", "finish": "MESSAGE_QUEUE", "bidi": false },
        "READ_OBJECT": { "start": "CONTAINER_ECS", "finish": "STORE_OBJECT", "bidi": false },
        "WRITE_OBJECT": { "start": "CONTAINER_ECS", "finish": "STORE_OBJECT", "bidi": false }
      }
    },
    "custom": {
      "icon": "fas:code",
      "template": "template.ts"
    }
  }
}
